# Generated by Django 5.1.7 on 2025-06-06 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='roomallocation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roommaintenance',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roommaintenance',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_maintenance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roommaintenance',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='rooms.room'),
        ),
        migrations.AlterUniqueTogether(
            name='roomallocation',
            unique_together={('room', 'student', 'check_in_date')},
        ),
    ]
